### ISSUE TITLE
A problem while lauching the code

### ISSUE THREAD

**Issue by Festouille** [silvestrodecaro/microsoft-account-creator#11]
```
[11:20:33] Starting...
[11:20:33] Fetching Fingerprint...
undefined:1
<html>
^

SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\microsoft-account-creator\node_modules\bas-remote-node\src\services\utils.js:15:22)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by Festouille** [comment]
Hey, I already tried this morning, I also used a fork called mc-gen, it had the same problem, yesterday or two days ago it was fine

**Comment by Festouille** [comment]
I just tried right now, still the same issue !



```
PS C:\Users\akram> # Clone the repository
>> git clone https://github.com/silvestrodecaro/microsoft-account-creator.git
>> cd microsoft-account-creator
>> 
>> # Install dependencies
>> npm install
Cloning into 'microsoft-account-creator'...
remote: Enumerating objects: 380, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (91/91), done.
remote: Total 380 (delta 25), reused 34 (delta 16), pack-reused 272 (from 1)
Receiving objects: 100% (380/380), 3.20 MiB | 6.19 MiB/s, done.
Resolving deltas: 100% (171/171), done.
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'node-gyp-load@0.0.5',
npm warn EBADENGINE   required: { npm: '^8.5.0', node: '>=16.0.0' },
npm warn EBADENGINE   current: { node: 'v20.18.0', npm: '10.9.0' }
npm warn EBADENGINE }

added 278 packages, and audited 279 packages in 17s

84 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\akram\microsoft-account-creator> npm install
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: 'node-gyp-load@0.0.5',
[13:32:41] Starting...
[13:32:41] Fetching Fingerprint...
undefined:1
<html>
^

SyntaxError: Unexpected token '<', "<html>
<h"... is not valid JSON
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\akram\microsoft-account-creator\node_modules\bas-remote-node\src\services\utils.js:15:22)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.18.0
PS C:\Users\akram\microsoft-account-creator>
```

**Comment by TOBIBLASTER00912** [comment]
same for me, i have the same issue

**Comment by silvestrodecaro** [comment]
As you can see here https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/137, there was an issue with the puppeteer-with-fingerprints library that caused a regression in my code. I just committed an update that fixes it. Try it and let me know! ;)

**Comment by Festouille** [comment]
It is working now, thank you so much for your help & your code ! 

```
[14:59:30] Fingerprint fetched and applied
[14:59:30] Launching browser...
```
